server {
  # Écoute les requêtes sur le port 9000
  listen 9000;

  # Définit le nom du serveur en local
  server_name localhost;

  # Définit le dossier où se trouvent les fichiers du site
  root /var/www/html/softy-pinko-front-end;

  # Définit le fichier chargé par défaut
  index index.html;

  # Gère les requêtes vers la racine du site
  location / {
    # Cherche d’abord le fichier demandé, puis le dossier correspondant, sinon renvoie une erreur 404
    try_files $uri $uri/ =404;
  }
}